site_name: PandasAI
site_url: https://pandasai.readthedocs.io/en/latest/
repo_url: https://github.com/gventuri/pandas-ai
edit_uri: https://github.com/gventuri/pandas-ai/blob/main/docs/
site_description: PandasAI is a Python library that integrates generative artificial intelligence capabilities into pandas, making dataframes conversational
site_author: Gabriele Venturi

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Connectors:
      - connectors.md
  - LLMs:
      - LLMs/llms.md
  - Pipelines:
      - pipelines/pipelines.md
  - Advanced usage:
      - cache.md
      - custom-head.md
      - fields-description.md
      - train.md
      - custom-response.md
      - custom-whitelisted-dependencies.md
      - skills.md
      - determinism.md
  - Examples:
      - examples.md
  - About:
      - Contributing: CONTRIBUTING.md
      - License: license.md
extra:
  version: "2.0"
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
