site_name: PandasAI
site_url: https://pandasai.readthedocs.io/en/latest/
repo_url: https://github.com/gventuri/pandas-ai
site_description: PandasAI is a Python library that integrates generative artificial intelligence capabilities into pandas, making dataframes conversational
site_author: Gabriele Venturi

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - LLMs:
      - LLMs/llms.md
      - LLMs/langchain.md
  - Advanced usage:
      - shortcuts.md
      - custom-head.md
      - save-dataframes.md
      - cache.md
      - middlewares.md
      - callbacks.md
      - custom-prompts.md
      - custom-optional-dependencies.md
  - Command Line Tool: pai_cli.md
  - API:
      - API/pandasai.md
      - API/prompts.md
      - API/llms.md
      - API/helpers.md
      - API/pai.md
  - About:
      - Release Notes: release-notes.md
      - Contributing: CONTRIBUTING.md
      - Documents Building: building_docs.md
      - License: license.md
extra:
  version: "1.2.1"
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
